// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.7
// source: protos/Message.proto

package protoMessage

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MessageServiceClient is the client API for MessageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MessageServiceClient interface {
	ConnectUsers(ctx context.Context, opts ...grpc.CallOption) (MessageService_ConnectUsersClient, error)
	PermissionToConnect(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error)
	ConnectToChannel(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error)
	Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PingResponse, error)
}

type messageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMessageServiceClient(cc grpc.ClientConnInterface) MessageServiceClient {
	return &messageServiceClient{cc}
}

func (c *messageServiceClient) ConnectUsers(ctx context.Context, opts ...grpc.CallOption) (MessageService_ConnectUsersClient, error) {
	stream, err := c.cc.NewStream(ctx, &MessageService_ServiceDesc.Streams[0], "/MessageService/ConnectUsers", opts...)
	if err != nil {
		return nil, err
	}
	x := &messageServiceConnectUsersClient{stream}
	return x, nil
}

type MessageService_ConnectUsersClient interface {
	Send(*Message) error
	Recv() (*Message, error)
	grpc.ClientStream
}

type messageServiceConnectUsersClient struct {
	grpc.ClientStream
}

func (x *messageServiceConnectUsersClient) Send(m *Message) error {
	return x.ClientStream.SendMsg(m)
}

func (x *messageServiceConnectUsersClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *messageServiceClient) PermissionToConnect(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/MessageService/PermissionToConnect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) ConnectToChannel(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/MessageService/ConnectToChannel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, "/MessageService/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessageServiceServer is the server API for MessageService service.
// All implementations must embed UnimplementedMessageServiceServer
// for forward compatibility
type MessageServiceServer interface {
	ConnectUsers(MessageService_ConnectUsersServer) error
	PermissionToConnect(context.Context, *Message) (*Message, error)
	ConnectToChannel(context.Context, *Message) (*Message, error)
	Ping(context.Context, *Empty) (*PingResponse, error)
	mustEmbedUnimplementedMessageServiceServer()
}

// UnimplementedMessageServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMessageServiceServer struct {
}

func (UnimplementedMessageServiceServer) ConnectUsers(MessageService_ConnectUsersServer) error {
	return status.Errorf(codes.Unimplemented, "method ConnectUsers not implemented")
}
func (UnimplementedMessageServiceServer) PermissionToConnect(context.Context, *Message) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PermissionToConnect not implemented")
}
func (UnimplementedMessageServiceServer) ConnectToChannel(context.Context, *Message) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConnectToChannel not implemented")
}
func (UnimplementedMessageServiceServer) Ping(context.Context, *Empty) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedMessageServiceServer) mustEmbedUnimplementedMessageServiceServer() {}

// UnsafeMessageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MessageServiceServer will
// result in compilation errors.
type UnsafeMessageServiceServer interface {
	mustEmbedUnimplementedMessageServiceServer()
}

func RegisterMessageServiceServer(s grpc.ServiceRegistrar, srv MessageServiceServer) {
	s.RegisterService(&MessageService_ServiceDesc, srv)
}

func _MessageService_ConnectUsers_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MessageServiceServer).ConnectUsers(&messageServiceConnectUsersServer{stream})
}

type MessageService_ConnectUsersServer interface {
	Send(*Message) error
	Recv() (*Message, error)
	grpc.ServerStream
}

type messageServiceConnectUsersServer struct {
	grpc.ServerStream
}

func (x *messageServiceConnectUsersServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func (x *messageServiceConnectUsersServer) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _MessageService_PermissionToConnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).PermissionToConnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MessageService/PermissionToConnect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).PermissionToConnect(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_ConnectToChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).ConnectToChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MessageService/ConnectToChannel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).ConnectToChannel(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MessageService/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).Ping(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// MessageService_ServiceDesc is the grpc.ServiceDesc for MessageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MessageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "MessageService",
	HandlerType: (*MessageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PermissionToConnect",
			Handler:    _MessageService_PermissionToConnect_Handler,
		},
		{
			MethodName: "ConnectToChannel",
			Handler:    _MessageService_ConnectToChannel_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _MessageService_Ping_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ConnectUsers",
			Handler:       _MessageService_ConnectUsers_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "protos/Message.proto",
}
